#:schema disabled
name = "db-service"
compatibility_date = "2024-04-03"
main = "src/index.ts"

[[d1_databases]]
binding = "D1"
database_name = "vonbergen-jobs"
database_id = "3ed68787-58b0-47e2-8195-cef1e03df0fd"

[[services]]
binding = "STORE"
service = "db-service"
entrypoint = "AdminStore"

